version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "500m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["443:443"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_CLUSTER_NAME: "VMware Tanzu Cloud Native Architect"
      CONCOURSE_EXTERNAL_URL: https://concourse.wdc.lab
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: user:password
      CONCOURSE_MAIN_TEAM_LOCAL_USER: devops,member,operator,viewer
      CONCOURSE_MAIN_TEAM_CONFIG: /concourse-keys/web_role_permission
      CONCOURSE_TLS_CERT: /concourse-keys/concourse_cert
      CONCOURSE_TLS_KEY: /concourse-keys/concourse_key
      CONCOURSE_TLS_BIND_PORT: 443
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "500m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      # enable DNS proxy to support Docker's 127.x.x.x DNS server
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      iCONCOURSE_CONTAINERD_DNS_SERVER: "10.79.142.21,10.79.142.22"
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "500m"
